/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Titanium SDK
 * Copyright TiDev, Inc. 04/07/2022-Present
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 *
 */
package ti.verticalpager;

import org.appcelerator.kroll.KrollDict;
import org.appcelerator.kroll.KrollModule;
import org.appcelerator.kroll.annotations.Kroll;

import org.appcelerator.titanium.TiApplication;
import org.appcelerator.kroll.common.Log;


@Kroll.module(name="TiVerticalPager", id="ti.verticalpager")
public class TiVerticalPagerModule extends KrollModule
{
	@Kroll.constant
	public static final int INDICATOR_TYPE_HORIZONTAL = 0;

	@Kroll.constant
	public static final int INDICATOR_TYPE_VERTICAL = 1;
	private static final String LCAT = "TiVerticalPager";

	public TiVerticalPagerModule()
	{
		super();
	}

	@Kroll.onAppCreate
	public static void onAppCreate(TiApplication app)
	{
		// Module initialization
		Log.d(LCAT, "onAppCreate - Module initialization");
		// put module init code that needs to run when the application is created
	}

	@Kroll.method
	public TiVerticalPagerProxy createView(KrollDict options) {
		TiVerticalPagerProxy proxy = new TiVerticalPagerProxy();

		if (options != null) {
			proxy.handleCreationDict(options);
		}

		return proxy;
	}
}

